export type ContentKind = "prompt" | "playbook" | "source" | "template" | "guide";
export type ContentDomain = "onboarding" | "roles" | "ui" | "d3" | "ops" | "templates" | string;
export type SiteLanguage = "en" | "ko";
export type ContentDifficulty = "starter" | "intermediate" | "advanced";
export type ContentCopyReadiness = "ready" | "guided" | "reference";
export type ContentArtifactType = "dossier" | "prompt" | "playbook" | "reference";
export type ContentRiskLevel = "low" | "medium" | "high" | "critical";

export type LocalizedContentData = {
  title: string;
  summary: string;
  body: string;
  html: string;
  toc: Array<{ id: string; title: string; level: number }>;
  promptBlock?: string | null;
  situationLead?: string | null;
  summaryPoints: string[];
  failurePoints: string[];
};

export type ContentMeta = {
  title: string;
  kind: ContentKind;
  domain: ContentDomain;
  summary: string;
  tags: string[];
  useCase: string;
  role: string;
  scenario: string;
  legacySurface: string;
  targetArchitecture: string;
  artifactType: ContentArtifactType;
  riskLevel: ContentRiskLevel;
  variantGroup: string;
  isDossier: boolean;
  archive: boolean;
  difficulty: ContentDifficulty;
  timeToUse: number;
  copyReadiness: ContentCopyReadiness;
  workflowGroup: string;
  featured: boolean;
  order?: number;
  next?: string | null;
  related?: string[];
};

export type ContentRecord = ContentMeta & {
  slug: string[];
  route: string;
  path: string;
  body: string;
  html: string;
  toc: Array<{ id: string; title: string; level: number }>;
  promptBlock?: string | null;
  nextRoute?: string | null;
  nextLink?: ContentLink | null;
  prevLink?: ContentLink | null;
  sequenceIndex?: number | null;
  sequenceTotal?: number | null;
  sequenceLinks: ContentLink[];
  relatedRoutes: ContentLink[];
  dossierLinks: ContentLink[];
  variantLinks: ContentLink[];
  verificationLinks: ContentLink[];
  situationLead?: string | null;
  summaryPoints: string[];
  failurePoints: string[];
  locales: Record<SiteLanguage, LocalizedContentData>;
};

export type ContentLink = {
  title: string;
  route: string;
  summary: string;
  kind: ContentKind;
  domain: ContentDomain;
  useCase: string;
  role: string;
  scenario: string;
  legacySurface: string;
  targetArchitecture: string;
  artifactType: ContentArtifactType;
  riskLevel: ContentRiskLevel;
  variantGroup: string;
  isDossier: boolean;
  archive: boolean;
  difficulty: ContentDifficulty;
  timeToUse: number;
  copyReadiness: ContentCopyReadiness;
  workflowGroup: string;
  featured: boolean;
  order?: number;
  locales: Record<SiteLanguage, Pick<LocalizedContentData, "title" | "summary">>;
};
